var movieObect = {
    movieName: "شب های مافیا: &nbspزودیاک",
    movieTime: "۱۴۵ دقیقه",
    imgPoster: "../image/mov_cvr_137093_1712.webp",
    movieType: "گیم شو",
    familyTag: "خانوادگی",
    imdbRate: 4.2 / 20,
    thoumbnail: "assets/image/mov_137093_151345.webp",
    madeBy: "ایران",
    dateCreate: "۱۴۰۲",
    storyTitle: "داستان شوی شب های مافیا: زودیاک",
    storyDescription: "«شب های مافیا»، گیم شوی جذابی است که در آن یک قاتل سریالی به نام «زودیاک»، شهروندان و مافیای سیسیل را هدف قرار می دهد. در این برنامه محمد بحرانی نقش گرداننده بازی را بر عهده دارد.",
    aboutTitle: "درباره شوی شب های مافیا: زودیاک",
    aboutDescription: "سریال شب های مافیا: زودیاک به کارگردانی محمدرضا رضائیان در سال ۱۴۰۲ ساخته شده است. این سریال محصول کشور ایران و در ژانر گیم شو و خانوادگی می‌باشد.",
    aboutImg: "assets/image/53901789-8819-b__3218.webp",
    episodeTitleAll: "قسمت‌های شب های مافیا: زودیاک",
    episodeTitle12: "شوی شب های مافیا: زودیاک - فصل ۱ قسمت ۱۲",
    episodeDescriptionAll: "«شب های مافیا»، گیم شوی جذابی است که در آن یک قاتل سریالی به نام «زودیاک»، شهروندان و مافیای سیسیل را هدف قرار می دهد. در این برنامه محمد بحرانی نقش گرداننده بازی را بر عهده دارد.",
    episodeTime12: "۰۲:۵۰:۴۹",
    episodeImg12: "assets/image/mov_140115_66610.webp",
    episodeTitle11: "شوی شب های مافیا: زودیاک - فصل ۱ قسمت ۱۱",
    episodeTime11: "۰۲:۳۷:۲۱",
    episodeImg11: "assets/image/mov_139875_66214.webp",
    episodeTitle10: "شوی شب های مافیا: زودیاک - فصل ۱ قسمت ۱۰",
    episodeTime10: "۰۳:۰۵:۲۷",
    episodeImg10: "assets/image/mov_139727_65952.webp",
    episodeTitle9: "شوی شب های مافیا: زودیاک - فصل ۱ قسمت ۹",
    episodeTime9: "۰۲:۲۴:۴۰",
    episodeImg9: "assets/image/mov_139575_65449.webp",
    episodeTitle8: "شوی شب های مافیا: زودیاک - فصل ۱ قسمت ۸",
    episodeTime8: "۰۲:۲۰:۰۸",
    episodeImg8: "assets/image/mov_139392_65072.webp",
    episodeTitle7: "شوی شب های مافیا: زودیاک - فصل ۱ قسمت ۷",
    episodeTime7: "۰۲:۳۶:۳۵",
    episodeImg7: "assets/image/mov_139168_64857.webp",
    episodeTitle6: "شوی شب های مافیا: زودیاک - فصل ۱ قسمت ۶",
    episodeTime6: "۰۳:۰۵:۲۶",
    episodeImg6: "assets/image/mov_138953_64779.webp",
    episodeTitle5: "شوی شب های مافیا: زودیاک - فصل ۱ قسمت ۵",
    episodeTime5: "۰۲:۴۸:۳۶",
    episodeImg5: "assets/image/mov_138750_64406.webp",
    episodeTitle4: "شوی شب های مافیا: زودیاک - فصل ۱ قسمت ۴",
    episodeTime4: "۰۲:۴۸:۴۴",
    episodeImg4: "assets/image/mov_138498_63954.webp",
    episodeTitle3: "شوی شب های مافیا: زودیاک - فصل ۱ قسمت ۳",
    episodeTime3: "۰۲:۰۸:۴۲",
    episodeImg3: "assets/image/mov_137503_62992.webp",
    episodeTitle2: "شوی شب های مافیا: زودیاک - فصل ۱ قسمت ۲",
    episodeTime2: "۰۲:۱۱:۴۴",
    episodeImg2: "assets/image/mov_137502_62093.webp",
    episodeTitle1: "شوی شب های مافیا: زودیاک - فصل ۱ قسمت ۱",
    episodeTime1: "۰۲:۲۵:۱۳",
    episodeImg1: "assets/image/mov_137105_61943.webp",
    episodeTitle0: "آموزش شب های مافیا: زودیاک",
    episodeTime0: "۰۷:۴۵",
    episodeImg1: "assets/image/mov_137339_61705.webp",
    movieProposalCoverAll: "assets/image/exclusive-fa.svg",
    movieProposalName1: "شب های مافیا ۴",
    movieProposalName1Hover1: "گیم شو - خانوادگی",
    movieProposalName1Hover2: "۱۴۰۰&nbsp- ایران - زیرنویس دارد &nbsp",
    movieProposalName1Img1: "assets/image/mov_111307_32603-b.webp",
    movieProposalName2: "شب های مافیا ۳",
    movieProposalName2Hover1: "خانوادگی - درام",
    movieProposalName2Hover2: "۱۴۰۰&nbsp- ایران - زیرنویس دارد &nbsp",
    movieProposalName2Img2: "assets/image/mov_srl_89754_208-b.webp",
    movieProposalName3: "شب های مافیا ۲ ",
    movieProposalName3Hover1: "خانوادگی - درام",
    movieProposalName3Hover2: "۱۴۰۱&nbsp- ایران - زیرنویس دارد &nbsp",
    movieProposalName3Img2: "assets/image/mov_131274_53141-b.webp",
    movieProposalName4: "ارتش سری",
    movieProposalName4Hover1: "ریلیتی شو - گیم شو",
    movieProposalName4Hover2: "۱۳۹۹&nbsp- ایران - زیرنویس دارد &nbsp",
    movieProposalName4Img2: "assets/image/mov_131274_53141-b.webp",
    movieProposalName5: "شب های مافیا",
    movieProposalName5Hover1: "خانوادگی - درام",
    movieProposalName5Hover2: "۱۳۹۹&nbsp- ایران - زیرنویس دارد &nbsp",
    movieProposalName5Img2: "assets/image/mov_131274_53141-b.webp",
    castsTitleAll: "سایر عوامل سریال شب های مافیا: زودیاک",
    director: "محمدرضا رضائیان",
    producer: "محمدرضا رضائیان",
    conductor: "محمد بحرانی",
    supervisorOfAuthors: "مسعود سرافراز",
    writer1: "سعید نفسی",
    writer2: "سینا قلیچ خوانی",
    editor: "منصور نیک خواه خوش کلام",
    soundRecordingDirector: "فرهاد امامی",
    productionManager: "حسین امیری",
    photographer1: "رضا نعمت",
    photographer2: "نفس وطن خواه",
    dressDesigner: "نازنین خزایی",
    executiveProducer: "حمید مراوندی",
    artDirector: "محمد مراوندی",
    commentTitle: "دیدگاه‌های سریال شب های مافیا: زودیاک",
    seriesNumber: "فصل اول- قسمت ۱",
}